name: Gradle Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gradle:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
         gradle-version: 8.10

    # Build the project
    - name: Execute Gradle build
      run: ./gradlew build

      # Run SpotBugs for static analysis
    - name: Run SpotBugs
      run: ./gradlew spotbugsMain

      # Run Checkstyle for code quality checks
    - name: Run Checkstyle
      run: ./gradlew checkstyleMain

      # Run Pitest for mutation testing
    - name: Run Pitest Mutation Testing
      run: ./gradlew pitest

      # Generate jacoco report
    - name: Upload Jacoco Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: build/reports/jacoco/test/html

      # Upload Pitest report
    - name: Upload Pitest Mutation Testing Report
      uses: actions/upload-artifact@v4
      with:
        name: pitest-report
        path: build/reports/pitest


